networks:
  blockchain_network:
    driver: bridge

services:
  staker10:
    build:
      context: .
    container_name: staker10
    environment:
      - NODE_NAME=staker10
      - SHARD=shard10
    networks:
      - blockchain_network
    ports:
      - 5010:5000
      - 8001:8000
    volumes:
      - ./data:/app/data

  staker20:
    build:
      context: .
    container_name: staker20
    environment:
      - NODE_NAME=staker20
      - SHARD=shard20
    networks:
      - blockchain_network
    ports:
      - 5020:5000
      - 8002:8000
    volumes:
      - ./data:/app/data

  miner11:
    build:
      context: .
    container_name: miner11
    environment:
      - NODE_NAME=miner11
      - SHARD=shard10
    networks:
      - blockchain_network
    ports:
      - 5011:5000

  miner12:
    build:
      context: .
    container_name: miner12
    environment:
      - NODE_NAME=miner12
      - SHARD=shard10
    networks:
      - blockchain_network
    ports:
      - 5012:5000

  miner21:
    build:
      context: .
    container_name: miner21
    environment:
      - NODE_NAME=miner21
      - SHARD=shard20
    networks:
      - blockchain_network
    ports:
      - 5021:5000

  miner22:
    build:
      context: .
    container_name: miner22
    environment:
      - NODE_NAME=miner22
      - SHARD=shard20
    networks:
      - blockchain_network
    ports:
      - 5022:5000
